{{- define "base.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.base.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.base.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.base.deployment.image }}:{{ .Values.base.deployment.tag }}"
          imagePullPolicy: {{ .Values.base.deployment.pullPolicy }}
          ports:
            - containerPort: {{ .Values.base.deployment.port | int }}
          {{- if .Values.base.external_secrets.secret }}
          envFrom:
            - secretRef:
                name: {{ .Values.base.external_secrets.secret }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.base.deployment.requests_cpu | quote }}
              memory: {{ .Values.base.deployment.requests_memory | quote }}
            limits:
              cpu: {{ .Values.base.deployment.limits_cpu | quote }}
              memory: {{ .Values.base.deployment.limits_memory | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.base.deployment.health_path }}
              port: {{ .Values.base.deployment.port | int }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: {{ .Values.base.deployment.health_path }}
              port: {{ .Values.base.deployment.port | int }}
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}
