{{- define "base.ingress" -}}
{{- if .Values.base.ingress.url }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.base.ingress.clusterIssuer }}
    {{- with .Values.base.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: traefik
  {{- if .Values.base.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.base.ingress.url }}
      secretName: {{ .Release.Name }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.base.ingress.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
{{- end }}
{{- end }}
